### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by davidshumway** [galbiston/geosparql-jena#7]
Starting with a 400MB triples file in N3 format.

Running the following command is resulting in a memory error:

```bash
$ java -jar jena-fuseki-geosparql-4.2.0.jar -rf ../gj/w.n3 \
  --index_expiry 50000000000000,500000000000,500000000000 -p 3034 -t ../gj/ \
  -t2 -dg -c -rg --inference --spatial_index ../gj/spatial.index`

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.github.andrewoma.dexx.collection.internal.hashmap.HashTrieMap.updated0(CompactHashMap.java:323)
	at com.github.andrewoma.dexx.collection.internal.hashmap.HashTrieMap.updated0(CompactHashMap.java:315)
	at com.github.andrewoma.dexx.collection.internal.hashmap.HashTrieMap.updated0(CompactHashMap.java:315)
	at com.github.andrewoma.dexx.collection.internal.hashmap.HashTrieMap.updated0(CompactHashMap.java:315)
	at com.github.andrewoma.dexx.collection.internal.hashmap.CompactHashMap.put(CompactHashMap.java:70)
	at com.github.andrewoma.dexx.collection.HashMap.put(HashMap.java:96)
	at com.github.andrewoma.dexx.collection.HashMap.put(HashMap.java:39)
	at org.apache.jena.atlas.lib.persistent.PMap.plus(PMap.java:67)
	at org.apache.jena.sparql.core.mem.PMapTripleTable.lambda$add$9(PMapTripleTable.java:136)
	at org.apache.jena.sparql.core.mem.PMapTripleTable$$Lambda$350/0x00000008403a6040.accept(Unknown Source)
	at org.apache.jena.sparql.core.mem.OrderedTupleTable.lambda$map$2(OrderedTupleTable.java:96)
	at org.apache.jena.sparql.core.mem.OrderedTupleTable$$Lambda$351/0x00000008403a5840.accept(Unknown Source)
	at org.apache.jena.sparql.core.mem.PMapTripleTable.add(PMapTripleTable.java:81)
	at org.apache.jena.sparql.core.mem.PMapTripleTable.add(PMapTripleTable.java:41)
	at org.apache.jena.sparql.core.mem.TriTable.lambda$add$1(TriTable.java:88)
	at org.apache.jena.sparql.core.mem.TriTable$$Lambda$349/0x00000008403a6c40.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.jena.sparql.core.mem.TriTable.add(TriTable.java:88)
	at org.apache.jena.sparql.core.mem.TriTable.add(TriTable.java:43)
	at org.apache.jena.sparql.core.mem.DatasetGraphInMemory$$Lambda$348/0x00000008403a6840.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.jena.sparql.core.mem.DatasetGraphInMemory.lambda$setDefaultGraph$10(DatasetGraphInMemory.java:335)
	at org.apache.jena.sparql.core.mem.DatasetGraphInMemory$$Lambda$346/0x00000008403a7c40.accept(Unknown Source)
	at org.apache.jena.sparql.core.mem.DatasetGraphInMemory.mutate(DatasetGraphInMemory.java:392)
	at org.apache.jena.sparql.core.mem.DatasetGraphInMemory.setDefaultGraph(DatasetGraphInMemory.java:333)
	at org.apache.jena.sparql.core.DatasetImpl.setDefaultModel(DatasetImpl.java:204)
	at org.apache.jena.geosparql.configuration.GeoSPARQLOperations.convertGeoPredicates(GeoSPARQLOperations.java:763)
	at org.apache.jena.fuseki.geosparql.DatasetOperations.setup(DatasetOperations.java:73)
	at org.apache.jena.fuseki.geosparql.Main.main(Main.java:64)
```

Also, out of curiosity, is there any way to allow an unlimited cache expire time (`index_expiry`)?

**Comment by galbiston** [comment]
`index_expiry` can be switched off by passing `0`, see #16 [GeoSPARQL Fuseki](https://jena.apache.org/documentation/geosparql/geosparql-fuseki.html). However, this will likely impact performance greatly. Perhaps try using the default value or small values, e.g. a few seconds.

The large values you have used effectively means that objects relating to the entire dataset are being retained in memory. These indexes are time based because the same literals are accessed and tested repeatedly in quick succession during querying. Retaining them for short periods avoids having to repeatedly extract the same information.

This is not the maintained project for GeoSPARQL Jena. It has all been transferred to the main Apache Jena project.
